### PR TITLE
created shared module

### PR DESCRIPTION
**Pull request by seymour-bootay**
added module for shared functionality and constants

### CODE REVIEW

**Comment by Cliabhach** [comment]
looks good. what's `shared/src/main/AndroidManifest.xml` doing in there though?

**Comment by seymour-bootay** [comment]
should library modules not have a manifest?

**Review by paulscott56 — COMMENTED** [review]
Great idea! Thanks for this module!

**Comment by Cliabhach** [comment]
@seymour-bootay i don't think they're read, although i could be wrong on that

**Pull request merged**
