### PR TITLE
Updated card view layouts to use androidx widget

### PR DESCRIPTION
**Pull request by milothomas**
Fixed error when inflating card views

### CODE REVIEW

**Comment by milothomas** [comment]
UI/UX improvements

**Comment by skraynick** [comment]
Will look at today.

**Comment by krisgesling** [comment]
Thanks @skraynick. 

Apologies for the request out of the blue too. I was trying to write a comment but Github was having a meltdown at the time.

**Comment by skraynick** [comment]
haha... no worries. I am blaming everything on the virus these days. All good. :D

**Review by skraynick — APPROVED** [review]
Looks good to me. With no complaints I can merge.

**Pull request merged**
