### PR TITLE
Cleaned up wear functionality.

### PR DESCRIPTION
**Pull request by seymour-bootay**
Made proposed changes and removed the retry loop in the sendMessage method (no longer needed).

### CODE REVIEW

**Comment by Cliabhach** [comment]
((cross-ref to issue #14))

**Comment by Cliabhach** [comment]
I'm the designated reviewer now....

By the way, you don't need to close pull requests every time you want to rewrite branch history. One PR per person per issue is plenty.

**Review by Cliabhach — APPROVED** [review]
Excellent!

**Comment by Cliabhach** [comment]
@seymour-bootay you want the honors, or should I do it?

**Comment by paulscott56** [comment]
All merged now! Thank you for your hard work!

**Comment by Cliabhach** [comment]
@paulscott56 out of left field there! Did you ever assign #14 to @seymour-bootay ?

**Pull request merged**
