### PR TITLE
upgraded gradle dependencies.

### PR DESCRIPTION
**Pull request by skraynick**

### CODE REVIEW

**Comment by paulscott56** [comment]
Who is currently reviewing PR's?

**Comment by skraynick** [comment]
NO one, except me, but no good to review my own changes. ;)

**Review by paulscott56 — APPROVED** [review]
Simple update on versions. Seems OK!

**Comment by skraynick** [comment]
Thanks. Next one for kotlin will be big.

**Comment by paulscott56** [comment]
No problem. I'll do a full review on that one then!

**Pull request merged**
