### PR TITLE
Feature/port to kotlin

### PR DESCRIPTION
**Pull request by skraynick**

### CODE REVIEW

**Comment by skraynick** [comment]
@paulscott56 please can you start looking over. Thanks. Be kind. I am new to kotlin. I left the tests for now.

**Comment by paulscott56** [comment]
Can you update to kotlin-1.2.41?

**Comment by skraynick** [comment]
Sure, in the next week or so, just got back from defcon and catching up on work-work.

**Comment by skraynick** [comment]
@paulscott56 done. Thanks.

**Comment by skraynick** [comment]
@paulscott56 can you merge please. thanks

**Pull request merged**
